name: PR-Pipeline
on:
  pull_request:
    branches:
      - master

jobs:
  pr-pipline:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: action/checkout@v2

      - name: Setup Node
        use: actions/setup-node@v2
        with:
          node-version: '18.18.1'

      - name: install dependencies
        run: npm install |
             npm install -g pnpm |
             pnpm install |
             pnpm dev   




