name: Release Discord Notification
run-name: ${{ github.ref_name }} is notify releasing ✨

on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.13.1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          color: "2105893"
          username: "Release Changelog"
          avatar_url: "https://cdn.discordapp.com/avatars/396662502076841984/664233da95097fc5fed92e57107f1b18.png"
          footer_title: "Changelog"
          footer_icon_url: "https://cdn.discordapp.com/avatars/396662502076841984/664233da95097fc5fed92e57107f1b18.png"
          footer_timestamp: true
