name: PR-Pipeline
on:
  pull_request:

  workflow_dispatch:

jobs:
  pr-pipline:
    runs-on: [self-hosted]
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install dependencies
        uses: ./.github/actions/pnpm-install@

      - name: build env
        shell: bash
        run: pnpm dev





