name: PR-Pipeline
on:
  pull_request:
    # branches:
    #   -master

  workflow_dispatch:

jobs:
  pr-pipline:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.1'

      - name: install dependencies
        shell: bash
        run: npm install |
             npm install -g pnpm |
             pnpm install |
             pnpm dev   




