name: PR-Pipeline
on:
  pull_request:

  workflow_dispatch:

jobs:
  pr-pipline:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: feature/GHA-PRpipeline

      - name: install dependencies
        uses: ./.github/actions/pnpm-install

      - name: build env
        shell: bash
        run: pnpm dev





